# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-04-14 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0002_tenant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='account',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
