# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-05-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0004_frontmach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('allocation', models.BooleanField()),
                ('designtime', models.DateField(auto_now=True)),
                ('descript', models.CharField(max_length=20)),
                ('upload', models.BooleanField()),
                ('size', models.IntegerField()),
                ('uploadtime', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
