# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-05-11 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='designtime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uploadtime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
