# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-05-11 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0006_auto_20160511_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='designtime',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='uploadtime',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
