# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160413143217 on 2016-05-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyWebApp', '0008_auto_20160512_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
